version: 2.1

orbs:
  android: circleci/android@2.0.0

jobs:
  unit-test:
    executor:
      name: android/android-machine
      tag: 2021.10.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - android/run-tests:
          test-command: ./gradlew testDebugUnitTest
      - android/save-gradle-cache
      - android/save-build-cache
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
  ktlint:
    executor:
      name: android/android-machine
      tag: 2021.10.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - android/run-tests:
          test-command: ./gradlew ktlintCheck
      - android/save-gradle-cache
      - android/save-build-cache
      - run:
          name: Save ktlint results
          command: |
            mkdir -p ~/test-results/ktlint/
            find . -type f -regex ".*/build/reports/ktlint/*/.*txt" -exec cp {} ~/test-results/ktlint/ \;
          when: always
      - store_artifacts:
          path: ~/test-results/ktlint

workflows:
  test:
    jobs:
      - unit-test
      - ktlint
